[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "interest"
description = "A python package to extract the sentiment of the historical Dutch news articles"
authors = [
    {name = "Shiva", email = "s.nadi@uu.nl"},
    {name = "Parisa Zahedi", email = "p.zahedi@uu.nl"}
]
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
]
dynamic = ["version"]
dependencies = [
    "numpy ~= 1.23.4",
    "pandas ~= 1.5.0",
    "gensim ~= 4.0.0",
    "nltk ~= 3.6.0",
    "tqdm ~= 4.62.0",
    "matplotlib ~= 3.5.0",
    "scikit-learn ~= 0.24.2"
]

[project.optional-dependencies]
lint = ["flake8"]
test = ["pytest", "mypy"]

[tool.setuptools]
packages = ["interest"]

[tool.flake8]
max-line-length = 99
